#!/bin/sh
# Requires brightnessctl, ddcutils, the i2c-dev kernel module
# User must be member of the i2c group

br=$(cat "/tmp/current_brightness" 2> /dev/null)
if [ $? -eq 1 ]; then
    {{#if laptop}}
    br="$(awk 'BEGIN {printf("%-3d\n", '"$(brightnessctl g)"' / '"$(brightnessctl m)"' * 100)}')"
    {{else }}
# If the file doesn't exist, we need to query 
# (ddcutil takes a long time, that's why we tried to avoid it)
    br=$(ddcutil getvcp 10 | sed -E 's/^.*current value =\s+//g;s/,.*$//g')
    {{/if }}
fi

# No arguments - query brightness level
if [ $# -eq 0 ]; then
    echo "$br"
else

    # Use the value '5' if 2nd argument is missing
    delta="${2:-5}"

    case "$1" in
	up) 
	    new=$((br+delta)) 
	    [ $new -gt 100 ] && new=100
	    ;;
	down) 
	    new=$((br-delta)) 
	    [ $new -lt 0 ] && new=0
	    ;;
    esac

    killall brightnessset 2> /dev/null
    echo $new > "/tmp/current_brightness" 2> /dev/null
    brightnessset &
    kill -RTMIN+2 $(pidof waybar)
fi

