#!/usr/bin/sh

delta="0.1"
file=/tmp/eww-brightness

case "$1" in
  up) busctl --user call rs.wl-gammarelay / rs.wl.gammarelay UpdateBrightness d $delta ;;
  down) busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateBrightness d -$delta ;;
  set) busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Brightness d $2 ;;
esac

brightness=$(printf %.0f $(echo "100 * \
  $(busctl --user get-property rs.wl-gammarelay / rs.wl.gammarelay Brightness \
    | sed 's/d //g')" | bc))

echo "$brightness" >> $file
