#!/usr/bin/sh

delta=5
file=/tmp/eww-volume
sink="@DEFAULT_SINK@"


get_volume() {
  volume=$(pactl get-sink-volume "$sink" | awk '{s=substr($5,0,length($5)-1);print s}')
}

get_volume
echo $volume

case "$1" in 
  up) pactl set-sink-volume "$sink" +$delta% ;;
  down) pactl set-sink-volume "$sink" -$delta% ;;
  mute) pactl set-sink-mute "$sink" toggle ;;
esac

if [ "yes" = $(pactl get-sink-mute "$sink" | awk '{print $2}') ]; then
  volume=0
else
  get_volume
fi

echo "$volume" >> $file
