#!/usr/bin/sh

delta=200
file=/tmp/eww-colortemp

case "$1" in
  up) busctl --user call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n $delta ;;
  down) busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n -$delta ;;
  set) busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q $2 ;;
esac

temp=$(busctl --user get-property rs.wl-gammarelay / rs.wl.gammarelay Temperature | sed 's/q //g')

echo "$temp" >> $file
