#!/bin/bash

{{#if riverwm}}
BINARY=$1
TAG=$2

riverctl enter-mode normal

riverctl set-focused-tags "$TAG"

if ! pgrep "$BINARY" > /dev/null; then
    $BINARY > /dev/null 2> /dev/null &
fi

{{else}}

swaymsg mode "default"

BINARY=$1
WORKSPACE=$2
SELECTOR=$3

swaymsg workspace "$WORKSPACE" > /dev/null

if ! pgrep "$BINARY" > /dev/null; then
    $BINARY > /dev/null 2> /dev/null &
else
    swaymsg "$SELECTOR" focus
fi
{{/if}}

