#!/usr/bin/sh

if [ "$1" ]; then
    branch=$1
else
    branch=$(git branch -a | fzf | sed 's/\*\?\s*//g')
fi

# Abort if trying to checkout the same commit when HEAD is detached
# This is necessary because comparison with the current branch does 
# not work in this case (detached HEAD is not a branch)
echo "$branch" | grep "HEAD" > /dev/null
[ $? -eq 0 ] && exit 0

current=$(git branch --show-current)

[ -z "$branch" ] && echo "Aborted" && exit 1

[ "$branch" = "$current" ] && exit 0

is_remote_branch=$(echo "$branch" | grep "^remotes/origin/.*")

if [ "$is_remote_branch" ]; then
    git checkout --track "$branch"
else
    git checkout "$branch"
fi
