#!/usr/bin/sh

# no worky...

class="scratchpad"

if [ 0 -eq $(hyprctl clients -j | jq -r "map(select(.class == \"$class\")) | length") ]
then
  exec alacritty --class $class &
  hyprctl dispatch focuswindow $class > /dev/null 
  hyprctl dispatch movetoworkspace special
fi

hyprctl dispatch togglespecialworkspace
 