#!/usr/bin/sh

terminal=0

while getopts c:e:w:t value
do
  case $value in
    c) class="$OPTARG" ;;
    e) executable="$OPTARG" ;;
    w) workspace="$OPTARG" ;;
    t) terminal=1 ;;
  esac
done

[ -z $class ] && echo 'window class not specified' && exit 1
: "${executable:=$class}"

if [ 0 -eq $(hyprctl clients -j | jq -r "map(select(.class == \"$class\")) | length") ]
then
  [ $workspace ] && hypr-workspace -w $workspace

  if [ 1 -eq $terminal ]; then
    alacritty --class $class -e $executable &
  else
    $executable &
  fi
else
  hypr-workspace -w $(hyprctl clients -j | jq -r "map(select(.class == \"$class\"))[0].workspace.id")
fi

hyprctl dispatch focuswindow $class > /dev/null
