#!/usr/bin/sh

while getopts c:e:t value
do
  case $value in
    c) class="$OPTARG" ;;
    e) executable="$optarg" ;;
    t) terminal=1 ;;
  esac
done

: "${executable:=$class}"

eww update "$executable-alive=true"

if [ 1 -eq $terminal ]; then
  alacritty --class $class -e $executable
else
  $executable
fi

eww update "$executable-alive=false"
