#!/usr/bin/sh
set -v

file="/tmp/hypr-active-workspaces"
default_primary=1
default_secondary=10
move=0

while getopts mw:d: value
do
  case $value in
    m) move=1 ;;
    w) workspace="$OPTARG" ;;
    d) direction="$OPTARG" ;;
  esac
done

is_primary=$((workspace % 2))

if [ 1 -eq $move ]; then
  hyprctl dispatch movetoworkspace $workspace
else
  hyprctl dispatch workspace $workspace
fi

# get other active workspace
if [ ! -e $file ]; then
  if [ 1 -eq $is_primary ]; then
    other_workspace=$default_secondary;
  else
    other_workspace=$default_primary;
  fi
else
  other_workspace=$(cat "$file" | tail -n 1 | jq ".[$is_primary]")
fi

# get all occupied workspaces
occupied=$(hyprctl clients -j | jq -rc "map(.workspace.id) | unique")

# write to file
if [ 1 -eq $is_primary ]; then
  new_string="[$workspace,$other_workspace,$occupied]"
else
  new_string="[$other_workspace,$workspace,$occupied]"
fi
echo $new_string >> $file
