#!/bin/sh

exit_if_no_changes() {
  [ -z "$(git status --short)" ] && echo "No changes made to workspace - skipping commit" && exit 0
}

save() {
  exit_if_no_changes
  git add .
  git commit -m "$(date "+%Y-%m-%d %I:%M:%S %p")"
  git push
}

workspace=$1
command=$2

cd "$workspace"

[ "$command" = "commit" ] && save && exit 0

git pull
nvim ./index.norg

save
