#!/bin/sh

save() {
  if [ -n "$(git status --short)" ]; then
    git add .
    git commit -m "$(date "+%Y-%m-%d %I:%M:%S %p")"
    git push
  else
    echo "No changes made to workspace - skipping commit"
  fi
}

workspace=$1
command=$2

cd "$workspace" || (echo "Workspace folder was not found" && exit 1)

save
[ "$command" = "commit" ] && exit 0

git pull
nvim ./index.norg

save
