#!/bin/sh

{{#if riverwm}}
riverctl enter-mode normal
{{else}}
swaymsg mode "default"
{{/if}}

result=$(echo "shutdown\nreboot\nsuspend" | wofi -d --prompt "Choose operation")

case "$result" in
    shutdown) shutdown now ;;
    reboot) reboot ;;
    suspend) systemctl suspend
esac

