#!/bin/sh

cmd_name=$1
if [ "$cmd_name" = "bemenu" ]; then
  cmd="bemenu --prompt 'Remake layout' -l "
else
  cmd="fzf --tail="
fi

layouts=$(fd . -e kdl /home/rg/.config/zellij/layouts | xargs basename -s .kdl)
layouts_len=$(echo "$layouts" | wc -l)
layout=$(echo "$layouts" | eval "$cmd$layouts_len" 2>/dev/null)

[ -z "$layout" ] && echo "Aborted" && exit 1

zellij d "$layout" --force
alacritty -e zellij -s "$layout" --layout "$layout"
