#!/usr/bin/sh

cmd_name=$1
if [ "$cmd_name" = "bemenu" ]; then
  cmd="bemenu --prompt 'Open layout' -l "
else
  cmd="fzf --tail="
fi

layouts=$(fd . -e kdl /home/rg/.config/zellij/layouts | xargs basename -s .kdl)
layouts_len=$(echo "$layouts" | wc -l)
layout=$(echo "$layouts" | eval "$cmd$layouts_len" 2>/dev/null)

[ -z "$layout" ] && echo "Aborted" && exit 1

sessions=$(zellij list-sessions --no-formatting)
current_session=$(echo "$sessions" | grep "(current)" | awk '{print $1}')
found_session=$(echo "$sessions" | awk '{print $1}' | grep -x "$layout")

if [ -n "$found_session" ]; then
  [ "$current_session" = "$found_session" ] && echo "You're already on this layout" && exit 1
  zellij kill-session "$current_session"
  alacritty -e zellij attach "$found_session"
else
  zellij kill-session "$current_session"
  alacritty -e zellij -s "$layout" --layout "$layout"
fi
