#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

riverctl csd-filter-add title spotify
riverctl float-filter-add title spotify

riverctl map normal Super Return spawn alacritty
riverctl map normal Super Q close
riverctl map normal Super+Shift F4 exit

# TODO: alt-tab shift-alt-tab
# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Alt Tab focus-view next
riverctl map normal Shift+Alt Tab focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Space zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Floating window controls
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100
# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view
# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super+Control F toggle-float

riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Control K send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Control J send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Control H send-layout-cmd rivertile "main-location left"

riverctl map normal Super P spawn "wofi --show=drun --prompt=Launch | xargs riverctl spawn"

riverctl map normal Super+Control S spawn "screenshot"
riverctl map normal Super+Control+Shift S spawn "screenshot full"

for mode in normal locked
do
    riverctl map $mode Super bracketleft spawn 'pulsemixer --change-volume -5'
    riverctl map $mode Super bracketright spawn 'pulsemixer --change-volume +5'
    riverctl map $mode Super+Control M spawn 'pulsemixer --toggle-mute'

    riverctl map $mode Super apostrophe spawn 'brightness up'
    riverctl map $mode Super semicolon spawn 'brightness down'
done

riverctl declare-mode command
riverctl map normal Super A enter-mode command
riverctl map command None Escape enter-mode normal

riverctl map command None 0 spawn 'riverctl enter-mode normal && plsdo power'
riverctl map command None 1 spawn 'riverctl enter-mode normal && plsdo keyboard_layout'
riverctl map command None 2 spawn 'riverctl enter-mode normal && ytdlmenu $(wl-paste) > /tmp/y.txt 2>&1'
riverctl map command Super K spawn 'focus_app krita 16'
riverctl map command None K spawn 'focus_app krita 16'
riverctl map command Super W spawn 'focus_app firefox 32'
riverctl map command None W spawn 'focus_app firefox 32'
riverctl map command Super S spawn 'focus_app spotify 128'
riverctl map command None S spawn 'focus_app spotify 128'
riverctl map command Super D spawn 'focus_app discord 256'
riverctl map command None D spawn 'focus_app discord 256'

riverctl background-color 0x191724
riverctl border-color-focused 0xf6c177
# Pull alpha to 80% (cc), same as the current alacritty opacity
riverctl border-color-unfocused 0x191724cc
riverctl border-width 4
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change
riverctl attach-mode bottom

riverctl xcursor-theme Bibata-Modern-Ice 36
gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Ice
gsettings set org.gnome.desktop.interface cursor-size 36

# Set keyboard repeat rate
riverctl set-repeat 50 250

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

riverctl spawn "swaybg -i ~/Pictures/Wallpapers/wall_tide.jpg -m fill"
riverctl spawn "waybar"
riverctl spawn "gammastep"
riverctl spawn "kanshi"
riverctl spawn "wired --run"

# TODO: update asus touchpad identifier
riverctl input "1267:5:Elan_Touchpad" accel-profile "flat"
riverctl input "1267:5:Elan_Touchpad" pointer-accel 0.5
riverctl input "1267:5:Elan_Touchpad" disable-while-typing disabled
riverctl input "1267:5:Elan_Touchpad" middle-emulation enabled
riverctl input "1267:5:Elan_Touchpad" natural-scroll enabled
riverctl input "1267:5:Elan_Touchpad" tap enabled

# riverctl keyboard-layout -variant basic -options caps:swapescape us
# riverctl keyboard-layout -variant 102_qwerty_dot_nodead -options caps:swapescape,altwin:menu_win hu 
# riverctl keyboard-layout -variant colemak_dh -options caps:swapescape,altwin:menu_win us
# riverctl keyboard-layout -variant colemak_dh_vim -options caps:swapescape,altwin:menu_win us
riverctl keyboard-layout -variant basic,102_qwerty_dot_nodead,colemak_dh,colemak_dh_vim -options caps:swapescape,altwin:menu_win,grp:ctrl_space_toggle us,hu,us,us

riverctl input "pointer-1241-44368-USB_Gaming_Mouse" accel-profile "flat"
riverctl input "pointer-1241-44368-USB_Gaming_Mouse" pointer-accel -0.5

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 8 -outer-padding 8

