[settings]
default_target_type = "template"

[alacritty.files]
"config/alacritty" = "~/.config/alacritty"

[alacritty.variables]
alacritty.font_size = 20
alacritty.opacity = 0.95

[btop.files]
"config/btop" = "~/.config/btop"

[colors.variables]
color.base = "#191724"
color.surface = "#1f1d2e"
color.overlay = "#26233a"
color.muted = "#6e6a86"
color.subtle = "#908caa"
color.text = "#e0def4"
color.love = "#eb6f92"
color.gold = "#f6c177"
color.rose = "#ebbcba"
color.pine = "#31748f"
color.foam = "#9ccfd8"
color.iris = "#c4a7e7"
color.hllow = "#21202e"
color.hlmed = "#403d52"
color.hlhi = "#524f67"
color.intel_blue = "#0071c5"
color.amd_red = "#ed1c24"

[desktop_entries.files]
"config/desktop_entries" = '~/.local/share/applications'

[dotfiles_id.files]
"config/dotfiles_id" = { target = "~/.config/dotfiles_id", type = "symbolic" }

[eww.files]
"config/eww" = "~/.config/eww"

[fish.files]
"config/fish" = "~/.config/fish"

[fontconfig.files]
"config/fontconfig" = "~/.config/fontconfig"

[git.files]
"config/git" = "~/.config/git"

[hypr.files]
"config/hypr" = "~/.config/hypr"
"config/hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"

[less.files]
"config/lesskey" = "~/.config/lesskey"

[mako.files]
"config/mako" = "~/.config/mako"

[mimeapps.files]
"config/mimeapps.list" = "~/.config/mimeapps.list"

[mpd.files]
"config/mpd" = "~/.config/mpd"

[ncmpcpp.files]
"config/ncmpcpp" = '~/.config/ncmpcpp'
"config/ncmpcpp/config" = { target = "~/.config/ncmpcpp/config", type = "symbolic" }

[newsboat.files]
"config/newsboat" = "~/.config/newsboat"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[scripts.files]
scripts = "~/.scripts"

[systemd.files]
"config/systemd/user" = "~/.config/systemd/user"

[transmission.files]
"config/transmission/bandwidth-groups.json" = "~/.config/transmission-daemon/bandwidth-groups.json"
"config/transmission/settings.json" = "~/.config/transmission-daemon/settings.json"

[tridactyl.files]
"config/tridactyl/tridactylrc" = "~/.config/tridactyl/tridactylrc"
"config/tridactyl/themes/sijink.css" = { target = "~/.config/tridactyl/themes/sijink.css", type = "symbolic" }

[wallpapers.files]
"kanehira_colors.jpg" = { target = "~/Pictures/Wallpapers/kanehira_colors.jpg", type = "symbolic" }
"kanehira_evening.jpg" = { target = "~/Pictures/Wallpapers/kanehira_evening.jpg", type = "symbolic" }

[x11.files]
".xinitrc" = "~/.xinitrc"

[x11.variables]
x11.enable = true

[yazi.files]
"config/yazi" = "~/.config/yazi/"
"config/yazi/theme.toml" = { target = "~/.config/yazi/theme.toml", type = "symbolic" }

[zathura.files]
"config/zathura" = '~/.config/zathura'

[zellij.files]
"config/zellij/config.kdl" = "~/.config/zellij/config.kdl"
"config/zellij/themes" = "~/.config/zellij/themes"
"config/zellij/layouts" = "~/.config/zellij/layouts"
"config/zellij/plugins" = { target = "~/.config/zellij/plugins", type = "symbolic" }
